### PR TITLE
Instantiate Show and Read in place of *ToStr / parse*

### PR DESCRIPTION
**Pull request by d3adb5**
Basic unit tests were added for `ReflogEntry`'s string conversion. The typeclasses `Read` and `Show` were instantiated, and the functions responsible for converting the data to `String` or parsing it from it were eliminated.

A fix was added in [50743f5](https://github.com/lucasoshiro/oshit/pull/3/commits/50743f54ddb315630d223339ed3604ad5d8049d7), addressing the fact that the old parse function dropped the first character of the author string.

### CODE REVIEW

**Comment by d3adb5** [comment]
Can't request the review through GitHub for some reason, so here's me requesting it, @lucasoshiro. Let me know what you think!

**Review by lucasoshiro — APPROVED** [review]
Tested here, it looks like everything is working!

**Comment by d3adb5** [comment]
Do you think I should combine #5 and this PR, @lucasoshiro? The reason I split them was because I felt there were just way too many commits.

**Comment by lucasoshiro** [comment]
> Do you think I should combine #5 and this PR, @lucasoshiro? The reason I split them was because I felt there were just way too many commits.

Hmmm, by now I think it would be better keeping them in different PRs, as I still need to review this one 😕

**Review by lucasoshiro — APPROVED** [review]
Thanks! I'm merging it!

**Pull request merged**
